Simplify "slug" formula using REGEX_REPLACE instead of SUBSTITUTE
UnlyEd/airtable-utils pull request #3
Opened 2022-02-03 14:05 UTC by kbsali

This will make the formula easier to maintain when new cases appear.

2022-02-03 14:38 UTC, Vadorequest requested changes
Thanks for the PR! It's less convoluted and makes it easier to maintain indeed. I added a few feedbacks that should be fixed.

Could you make a reproduction, like a table with 3 columns, one with the current formula, another with yours and another as input? I'd like to make some tests to make sure we don't bring a regression by updating it. I'll do it if you don't have the time. :)

2022-02-03 14:38 UTC, Vadorequest commented on formulas/slug.txt
> +), '[\--]+', '-'
`\--` does that mean it will replace an unlimited amount of occurrences of `-` if there are more than 2?

2022-02-03 14:38 UTC, Vadorequest commented on formulas/slug.txt
> +), '[žźż]+', 'y'
Typo, should be "z"

2022-02-03 14:38 UTC, Vadorequest commented on formulas/slug.txt
> +), '[öòóœøōõ]+', 'o'
`œ` should be replaced to `oe`, I guess

2022-02-03 14:38 UTC, Vadorequest commented on formulas/slug.txt
> +), '\s+', '-'
What does `s+` do?

2022-02-21 12:47 UTC, Vadorequest commented
@kbsali Thanks for the update, there are a couple questions left, would you mind answering them? :)

2022-10-25 15:33 UTC, closed without merging

2022-10-25 15:54 UTC, Vadorequest commented
@kbsali Sorry for not merging this, I wasn't confident about introducing regressions. I liked how elegant your solution is, but didn't take the time to test it thoroughly to make sure it wouldn't break anything. 

As I use this formula on dozens of projects, it's quite critical to ensure any change don't cause any regression.

2022-10-25 20:26 UTC, kbsali commented
no problem, I was just cleaning my open PRs! :)